
POST http://localhost:5237/api/date
Content-Type: application/json

{
    "startDate": "2022-08-18",
    "workingDays": 10
}
###

POST http://localhost:5237/api/date
Content-Type: application/json

{
    "startDate": "2024-06-15",
    "workingDays": 10
}
